### PR TITLE
feat(Post): Implement asset cover feature

### LINKED ISSUE #31: Show post cover image on home/post/posts page
[Issuehunt badges](https://issuehunt.io/r/saberland/create-portfolio/issues/31)

Use the `assets.cover` attribute.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)

### Submitted pull Requests
- [#124 feat(Post): Implement asset cover feature](https://issuehunt.io/r/saberland/create-portfolio/pull/124)
- [#94 feat(Post): Implement asset cover feature](https://issuehunt.io/r/saberland/create-portfolio/pull/94)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/saberland/create-portfolio/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by amedora**
fixed #31 

This PR is a continuation of #94 by @SpyTec.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#31: Show post cover image on home/post/posts page](https://issuehunt.io/repos/188773840/issues/31)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by SpyTec** [comment]
LGTM

**Comment by egoist** [comment]
hmm who should I reward 😅

**Comment by amedora** [comment]
50/50 would be reasonable if it's ok for @SpyTec .

**Comment by Venefilyn** [comment]
Sure! Works for me

**Comment by egoist** [comment]
Unfortunately that's not possible on IssueHunt, only one PR can be rewarded, so I gave it to @SpyTec who started this PR

**Pull request merged**
